In [48]:
import pandas as pd
df = pd.read_csv('train.csv')

In [49]:
for x in df['Category'].unique():
    df1 = df[df['Category'] == x]
    x = x.replace(' ', '_')
    df1.to_csv(f'{x}.csv', index=False)

In [50]:
import pandas as pd
df = pd.read_csv('Men_Tshirts.csv')

df = df.rename(columns={
        "attr_1": "color",
    "attr_2": "neck",
    "attr_3": "pattern",
    "attr_4": "print_or_pattern_type",
    "attr_5": "sleeve_length",
})

# Save the updated CSV
df.to_csv("Men_Tshirts.csv", index=False)

df.head()

,id,Category,len,color,neck,pattern,print_or_pattern_type,sleeve_length,attr_6,attr_7,attr_8,attr_9,attr_10
0,0,Men Tshirts,5,default,round,printed,default,short sleeves,NaN,NaN,NaN,NaN,NaN
1,1,Men Tshirts,5,multicolor,polo,solid,solid,short sleeves,NaN,NaN,NaN,NaN,NaN
2,2,Men Tshirts,5,default,polo,solid,solid,short sleeves,NaN,NaN,NaN,NaN,NaN
3,3,Men Tshirts,5,multicolor,polo,solid,solid,short sleeves,NaN,NaN,NaN,NaN,NaN
4,4,Men Tshirts,5,multicolor,polo,solid,solid,short sleeves,NaN,NaN,NaN,NaN,NaN

In [51]:
import pandas as pd
df = pd.read_csv('Sarees.csv')

df = df.rename(columns={
    df.columns[3]: "blouse_pattern",
    df.columns[4]: "border",
    df.columns[5]: "border_width",
    df.columns[6]: "color",
    df.columns[7]: "occasion",
    df.columns[8]: "ornamentation",
    df.columns[9]: "pallu_details",
    df.columns[10]: "pattern",
    df.columns[11]: "print_or_pattern_type",
    df.columns[12]: "transparency"
})

# Save the updated CSV
df.to_csv("Sarees.csv", index=False)

df.head()

,id,Category,len,blouse_pattern,border,border_width,color,occasion,ornamentation,pallu_details,pattern,print_or_pattern_type,transparency
0,7432,Sarees,10,same as saree,woven design,small border,multicolor,party,jacquard,woven design,zari woven,applique,no
1,7433,Sarees,10,NaN,zari,small border,cream,traditional,NaN,NaN,zari woven,elephant,no
2,7434,Sarees,10,NaN,zari,small border,white,party,NaN,NaN,zari woven,floral,no
3,7435,Sarees,10,same as saree,woven design,big border,default,traditional,NaN,same as saree,zari woven,ethnic motif,no
4,7436,Sarees,10,solid,no border,NaN,NaN,daily,NaN,NaN,NaN,NaN,yes

In [52]:
import pandas as pd
df = pd.read_csv('Kurtis.csv')

df = df.rename(columns={
    df.columns[3]: "color",
    df.columns[4]: "fit_shape",
    df.columns[5]: "length",
    df.columns[6]: "occasion",
    df.columns[7]: "ornamentation",
    df.columns[8]: "pattern",
    df.columns[9]: "print_or_pattern_type",
    df.columns[10]: "sleeve_length",
    df.columns[11]: "sleeve_styling"
})

# Save the updated CSV
df.to_csv("Kurtis.csv", index=False)

df.head()

,id,Category,len,color,fit_shape,length,occasion,ornamentation,pattern,print_or_pattern_type,sleeve_length,sleeve_styling,attr_10
0,25778,Kurtis,9,black,straight,knee length,daily,net,solid,solid,three-quarter sleeves,regular,NaN
1,25779,Kurtis,9,red,straight,knee length,daily,default,default,default,three-quarter sleeves,regular,NaN
2,25780,Kurtis,9,red,straight,knee length,daily,default,default,default,three-quarter sleeves,regular,NaN
3,25781,Kurtis,9,navy blue,straight,knee length,daily,default,default,default,three-quarter sleeves,regular,NaN
4,25782,Kurtis,9,black,straight,knee length,daily,default,default,default,three-quarter sleeves,regular,NaN

In [53]:
import pandas as pd
df = pd.read_csv('Women_Tshirts.csv')

df = df.rename(columns={
    df.columns[3]: "color",
    df.columns[4]: "fit_shape",
    df.columns[5]: "length",
    df.columns[6]: "pattern",
    df.columns[7]: "print_or_pattern_type",
    df.columns[8]: "sleeve_length",
    df.columns[9]: "sleeve_styling",
    df.columns[10]: "surface_styling"
})

# Save the updated CSV
df.to_csv("Women_Tshirts.csv", index=False)

df.head()

,id,Category,len,color,fit_shape,length,pattern,print_or_pattern_type,sleeve_length,sleeve_styling,surface_styling,attr_9,attr_10
0,32601,Women Tshirts,8,multicolor,loose,long,default,default,default,regular sleeves,NaN,NaN,NaN
1,32602,Women Tshirts,8,yellow,loose,long,default,default,long sleeves,regular sleeves,NaN,NaN,NaN
2,32603,Women Tshirts,8,multicolor,loose,long,default,default,default,regular sleeves,NaN,NaN,NaN
3,32604,Women Tshirts,8,multicolor,loose,long,default,default,long sleeves,regular sleeves,NaN,NaN,NaN
4,32605,Women Tshirts,8,multicolor,loose,long,default,default,default,regular sleeves,NaN,NaN,NaN

In [54]:
import pandas as pd
df = pd.read_csv('Women_Tops_&_Tunics.csv')

df = df.rename(columns={
    df.columns[3]: "color",
    df.columns[4]: "fit_shape",
    df.columns[5]: "length",
    df.columns[6]: "neck_collar",
    df.columns[7]: "occasion",
    df.columns[8]: "pattern",
    df.columns[9]: "print_or_pattern_type",
    df.columns[10]: "sleeve_length",
    df.columns[11]: "sleeve_styling",
    df.columns[12]: "surface_styling"
})

# Save the updated CSV
df.to_csv("Women_Tops_&_Tunics.csv", index=False)

df.head()

,id,Category,len,color,fit_shape,length,neck_collar,occasion,pattern,print_or_pattern_type,sleeve_length,sleeve_styling,surface_styling
0,51375,Women Tops & Tunics,10,black,regular,NaN,NaN,NaN,NaN,NaN,NaN,regular sleeves,NaN
1,51376,Women Tops & Tunics,10,navy blue,fitted,crop,high,casual,default,solid,short sleeves,default,knitted
2,51377,Women Tops & Tunics,10,red,regular,regular,round neck,casual,printed,typography,sleeveless,sleeveless,NaN
3,51378,Women Tops & Tunics,10,default,fitted,crop,stylised,casual,solid,solid,short sleeves,regular sleeves,default
4,51379,Women Tops & Tunics,10,default,boxy,regular,round neck,casual,printed,typography,short sleeves,default,NaN