The Cars93 dataset contains data from 93 cars that were on sale in the USA in 1993. The dataset has 93 rows listing various car models along with their features and specifications. The columns of this dataset---there are 27 of them---comprise various attributes, e.g., Manufacturer, Type, Price, mileage, horsepower etc.

## Reading csv file and storing it in pandas dataframe

In [2]:
import pandas as pd

# Getting started with pandas: https://pandas.pydata.org/docs/getting_started/index.html
# API reference: https://pandas.pydata.org/docs/reference/index.html
# Reading the data from a csv file and storing it in a panda dataframe
df = pd.read_csv("Cars93.csv")
df

,Serial No.,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240
92,93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,...,5,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850

In [ ]:
df.head() # prints top 5

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Diff. in Price
Serial No.,,,,,,,,,,,,,,,,,,,,,
1,Acura,Legend,Small,12.9,15.9,18.8,25,31,None,Front,...,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra,5.9
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend,9.5
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90,6.4
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100,13.8
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i,12.5

In [ ]:
df.tail(6)

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Diff. in Price
Serial No.,,,,,,,,,,,,,,,,,,,,,
88,Volkswagen,Fox,Small,8.7,9.1,9.5,25,33,None,Front,...,163,93,63,34,26.0,10.0,2240,non-USA,Volkswagen Fox,0.8
89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,Front,...,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan,6.1
90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,Front,...,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat,4.8
91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,Front,...,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado,0.8
92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,Rear,...,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240,1.7
93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,Front,...,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850,3.7

## Implicit and Explicit index

In [3]:
print(df.loc[1]['Model']) #explicit index
print(df.iloc[1]['Model']) #implicit index

Legend
Legend

We see no difference because the explicit index is the same as implicit index (0-based indexing)

In [5]:
df = df.set_index("Serial No.")
print(df.loc[1]['Model']) #explicit index # '2' can also be used instead of explicit 'Model'
print(df.iloc[1]['Model']) #implicit index

Integra
Legend

Now the explicit indexing has become 1-based, hence the difference in output.
Note: Implicit index always remains 0-based

## Basic operations

In [6]:
# accessing using column names
df['Manufacturer']

Serial No.
1          Acura
2          Acura
3           Audi
4           Audi
5            BMW
         ...
89    Volkswagen
90    Volkswagen
91    Volkswagen
92         Volvo
93         Volvo
Name: Manufacturer, Length: 93, dtype: object

In [ ]:
df['Diff. in Price'] = df['Max.Price'] - df['Min.Price'] #adding new column
df

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Diff. in Price
Serial No.,,,,,,,,,,,,,,,,,,,,,
1,Acura,Integra,Small,12.9,15.9,18.8,25,31,None,Front,...,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra,5.9
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend,9.5
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90,6.4
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100,13.8
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i,12.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,None,Front,...,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan,6.1
90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,None,Front,...,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat,4.8
91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,None,Front,...,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado,0.8
92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,Rear,...,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240,1.7
93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,Front,...,184,105,69,38,30.0,15.0,3245,non-USA,Volvo 850,3.7

In [ ]:
# changing values
print(df['Model'][1]) #explicit index used here
df['Model'][1] = 'Legend'
print(df['Model'][1]) #explicit index used here

Integra
Legend

<ipython-input-35-09dcbedf1265>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Model'][1] = 'Legend'

# Cleaning Data

## Empty Values
NaN Values

In [ ]:
df['Luggage.room']

Serial No.
1     11.0
2     15.0
3     14.0
4     17.0
5     13.0
      ...
89     NaN
90    14.0
91    15.0
92    14.0
93    15.0
Name: Luggage.room, Length: 93, dtype: float64

NaN values are missing values, not a number

If the dataset is big enough removing a few rows will not have a big impact on the result.

In [ ]:
new_df = df.dropna()
new_df['Luggage.room']

Serial No.
1     11.0
2     15.0
3     14.0
4     17.0
5     13.0
      ...
88    10.0
90    14.0
91    15.0
92    14.0
93    15.0
Name: Luggage.room, Length: 82, dtype: float64

The length is reduced from 93 to 82. Another way to deal with missing values is to replace the the NaN values with different values.

In [ ]:
new_df['Luggage.room'] = df["Luggage.room"].fillna(df["Luggage.room"].mean()) # here the NaN Values are replaced by mean.
new_df['Luggage.room']

<ipython-input-70-6498d8ccf748>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['Luggage.room'] = df["Luggage.room"].fillna(df["Luggage.room"].mean())

Serial No.
1     11.0
2     15.0
3     14.0
4     17.0
5     13.0
      ...
88    10.0
90    14.0
91    15.0
92    14.0
93    15.0
Name: Luggage.room, Length: 82, dtype: float64

# Removing Duplicates

In [ ]:
df.drop_duplicates(inplace = True) #drops all duplicate rows
df

# Sorting, grouping and printing

List all the manufacturers mentioned in the Cars93 data set in alphabetical order.

In [ ]:
df['Manufacturer'].sort_values().unique() # default is ascending order

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrylser', 'Chrysler', 'Dodge', 'Eagle', 'Ford', 'Geo', 'Honda',
       'Hyundai', 'Infiniti', 'Lexus', 'Lincoln', 'Mazda',
       'Mercedes-Benz', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile',
       'Plymouth', 'Pontiac', 'Saab', 'Saturn', 'Subaru', 'Suzuki',
       'Toyota', 'Volkswagen', 'Volvo'], dtype=object)

Print all details of the costliest car of each of the ‘Types’

In [ ]:
for i in df['Type'].unique():
    x = df.groupby('Type').get_group(i)  #groupby is used to categorise
    print(x[x['Price']==x['Price'].max()])

           Manufacturer   Model   Type  Min.Price  Price  Max.Price  MPG.city  \
Serial No.
1                 Acura  Legend  Small       12.9   15.9       18.8        25

            MPG.highway AirBags DriveTrain  ... Length  Wheelbase  Width  \
Serial No.                                  ...
1                    31    None      Front  ...    177        102     68

            Turn.circle  Rear.seat.room Luggage.room  Weight   Origin  \
Serial No.
1                    37            26.5         11.0    2705  non-USA

                     Make  Diff. in Price
Serial No.
1           Acura Integra             5.9

[1 rows x 28 columns]
             Manufacturer Model     Type  Min.Price  Price  Max.Price  \
Serial No.
59          Mercedes-Benz  300E  Midsize       43.8   61.9       80.0

            MPG.city  MPG.highway             AirBags DriveTrain  ... Length  \
Serial No.                                                        ...
59                19           25  Driver & Passenger       Rear  ...    187

            Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  \
Serial No.
59                110     69           37            27.0         15.0

            Weight   Origin                Make  Diff. in Price
Serial No.
59            3525  non-USA  Mercedes-Benz 300E            36.2

[1 rows x 28 columns]
             Manufacturer Model     Type  Min.Price  Price  Max.Price  \
Serial No.
58          Mercedes-Benz  190E  Compact       29.0   31.9       34.9

            MPG.city  MPG.highway      AirBags DriveTrain  ... Length  \
Serial No.                                                 ...
58                20           29  Driver only       Rear  ...    175

            Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  \
Serial No.
58                105     67           34            26.0         12.0

            Weight   Origin                Make  Diff. in Price
Serial No.
58            2920  non-USA  Mercedes-Benz 190E             5.9

[1 rows x 28 columns]
           Manufacturer     Model   Type  Min.Price  Price  Max.Price  \
Serial No.
52              Lincoln  Town_Car  Large       34.4   36.1       37.8

            MPG.city  MPG.highway             AirBags DriveTrain  ... Length  \
Serial No.                                                        ...
52                18           26  Driver & Passenger       Rear  ...    219

            Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  \
Serial No.
52                117     77           45            31.5         22.0

            Weight  Origin              Make  Diff. in Price
Serial No.
52            4055     USA  Lincoln Town_Car             3.4

[1 rows x 28 columns]
           Manufacturer     Model    Type  Min.Price  Price  Max.Price  \
Serial No.
19            Chevrolet  Corvette  Sporty       34.6   38.0       41.5

            MPG.city  MPG.highway      AirBags DriveTrain  ... Length  \
Serial No.                                                 ...
19                17           25  Driver only       Rear  ...    179

            Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  \
Serial No.
19                 96     74           43             NaN          NaN

            Weight  Origin                Make  Diff. in Price
Serial No.
19            3380     USA  Chevrolet Corvette             6.9

[1 rows x 28 columns]
           Manufacturer   Model Type  Min.Price  Price  Max.Price  MPG.city  \
Serial No.
87               Toyota  Previa  Van       18.9   22.7       26.6        18

            MPG.highway      AirBags DriveTrain  ... Length  Wheelbase  Width  \
Serial No.                                       ...
87                   22  Driver only        4WD  ...    187        113     71

            Turn.circle  Rear.seat.room Luggage.room  Weight   Origin  \
Serial No.
87                   41            35.0          NaN    3785  non-USA

                     Make  Diff. in Price
Serial No.
87          Toyota Previa             7.7

[1 rows x 28 columns]

Write a function that asks you to enter the name of a manufacturer and print all the
models produced by that manufacturer. Print an appropriate error message if the
input is invalid.

In [ ]:
def all_models(Manufacturer):
    if df['Manufacturer'][df['Manufacturer']==Manufacturer].count()==0:
        print('No Manufacturer found with this name.')
    else:
        print(df[df['Manufacturer']==Manufacturer])

all_models('Lincoln')

           Manufacturer        Model     Type  Min.Price  Price  Max.Price  \
Serial No.
51              Lincoln  Continental  Midsize       33.3   34.3       35.3
52              Lincoln     Town_Car    Large       34.4   36.1       37.8

            MPG.city  MPG.highway             AirBags DriveTrain  ... Length  \
Serial No.                                                        ...
51                17           26  Driver & Passenger      Front  ...    205
52                18           26  Driver & Passenger       Rear  ...    219

            Wheelbase  Width  Turn.circle  Rear.seat.room Luggage.room  \
Serial No.
51                109     73           42            30.0         19.0
52                117     77           45            31.5         22.0

            Weight  Origin                 Make  Diff. in Price
Serial No.
51            3695     USA  Lincoln Continental             2.0
52            4055     USA     Lincoln Town_Car             3.4

[2 rows x 28 columns]

Print the total count of cars per manufacturer.

In [ ]:
df.groupby('Manufacturer').size().reset_index(name='count')

     Manufacturer  count
0           Acura      2
1            Audi      2
2             BMW      1
3           Buick      4
4        Cadillac      2
5       Chevrolet      8
6        Chrylser      1
7        Chrysler      2
8           Dodge      6
9           Eagle      2
10           Ford      8
11            Geo      2
12          Honda      3
13        Hyundai      4
14       Infiniti      1
15          Lexus      2
16        Lincoln      2
17          Mazda      5
18  Mercedes-Benz      2
19        Mercury      2
20     Mitsubishi      2
21         Nissan      4
22     Oldsmobile      4
23       Plymouth      1
24        Pontiac      5
25           Saab      1
26         Saturn      1
27         Subaru      3
28         Suzuki      1
29         Toyota      4
30     Volkswagen      4
31          Volvo      2

List all the non-USA “Small” (‘Type’) cars (‘Make’) in alphabetical order.

In [ ]:
df[(df['Origin']=='non-USA') & (df['Type']=='Small')]['Make'].sort_values()

Serial No.
1         Acura Integra
39            Geo Metro
42          Honda Civic
45      Hyundai Elantra
44        Hyundai Excel
53            Mazda 323
54        Mazda Protege
62    Mitsubishi Mirage
64        Nissan Sentra
80         Subaru Justy
81        Subaru Loyale
83         Suzuki Swift
84        Toyota Tercel
88       Volkswagen Fox
Name: Make, dtype: object

Group the cars by ‘Manufacturer’ and find the average price for each of the manufacturers by averaging the ‘Price’ of all the models produced by a particular manufacturer and then print all the ‘Manufacturers’ sorted (in ascending order) by average price

In [ ]:
df.groupby('Manufacturer')['Price'].mean().sort_values()

Manufacturer
Suzuki            8.600000
Geo              10.450000
Hyundai          10.475000
Saturn           11.100000
Subaru           12.933333
Plymouth         14.400000
Mercury          14.500000
Ford             14.962500
Dodge            15.700000
Eagle            15.750000
Pontiac          16.140000
Honda            16.466667
Nissan           17.025000
Toyota           17.275000
Oldsmobile       17.500000
Mazda            17.600000
Volkswagen       18.025000
Chevrolet        18.187500
Mitsubishi       18.200000
Chrylser         18.400000
Buick            21.625000
Chrysler         22.650000
Volvo            24.700000
Acura            24.900000
Saab             28.700000
BMW              30.000000
Lexus            31.600000
Audi             33.400000
Lincoln          35.200000
Cadillac         37.400000
Mercedes-Benz    46.900000
Infiniti         47.900000
Name: Price, dtype: float64

Find the car models that are “Midsize” (‘Type’) and cost less than the average cost of all the cars (of all the types).

In [ ]:
df[(df['Type']=='Midsize') & (df['Price']<df['Price'].mean())]['Model']

Serial No.
6           Century
15           Lumina
27          Dynasty
47           Sonata
61           Cougar
69    Cutlass_Ciera
76       Grand_Prix
86            Camry
Name: Model, dtype: object

Find the car models that have MPG.city and MPG.highway higher than the average of MPG.city and average of MPG.highway, respectively. Here, average should be calculated over all the cars.

In [ ]:
df[(df['MPG.city']>df['MPG.city'].mean())&(df['MPG.highway']>df['MPG.highway'].mean())]['Model']

Serial No.
1            Legend
12         Cavalier
13          Corsica
23             Colt
29           Summit
31          Festiva
32           Escort
35            Probe
39            Metro
40            Storm
41          Prelude
42            Civic
43           Accord
44            Excel
46           Scoupe
53              323
54          Protege
55              626
62           Mirage
64           Sentra
65           Altima
68          Achieva
69    Cutlass_Ciera
72            Laser
73           LeMans
74          Sunbird
79               SL
80            Justy
81           Loyale
82           Legacy
83            Swift
84           Tercel
85           Celica
88              Fox
Name: Model, dtype: object

# Data derivation, computation and comparison

Calculate the ratio of Max.Price and Min.Price for each of the car models and add a new column called ‘Max_min_ratio’ to the imported dataframe.

1.   Print the cars for whom the ratio is equal to one.
2.   Find the manufacturer whom the gap between largest and smallest
max_min_ratio value is highest. Also, print the corresponding ratio values.
3. Print the car models (manufacturer and model) for whom the max_min_ratio is within ±1% of the mean of Max_min_ratio.

In [ ]:
df["Max_min_ratio"] = df["Max.Price"]/df["Min.Price"]
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Diff. in Price,Max_min_ratio
Serial No.,,,,,,,,,,,,,,,,,,,,,
1,Acura,Legend,Small,12.9,15.9,18.8,25,31,None,Front,...,102,68,37,26.5,11.0,2705,non-USA,Acura Integra,5.9,1.457364
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,115,71,38,30.0,15.0,3560,non-USA,Acura Legend,9.5,1.325342
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,102,67,37,28.0,14.0,3375,non-USA,Audi 90,6.4,1.247104
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,106,70,37,31.0,17.0,3405,non-USA,Audi 100,13.8,1.448052
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,109,69,39,27.0,13.0,3640,non-USA,BMW 535i,12.5,1.527426

In [ ]:
df[df["Max_min_ratio"] == 1]["Manufacturer"].values

array(['Buick', 'Chevrolet', 'Chrylser', 'Chrysler', 'Mazda', 'Mercury',
       'Oldsmobile'], dtype=object)

In [ ]:
grouped = df.groupby("Manufacturer").Max_min_ratio.agg(lambda x: x.max() - x.min())
new_df = grouped.reset_index() # Convert Series to Dataframe
solution = new_df["Manufacturer"].iloc[new_df["Max_min_ratio"].idxmax()]
print("Manufacturer with highest gap between largest and smallest max_min_ratio value is: ", solution)

Manufacturer with highest gap between largest and smallest max_min_ratio value is:  Chevrolet

In [ ]:
bool_series = df["Max_min_ratio"].between(0.99*df["Max_min_ratio"].mean(), 1.01*df["Max_min_ratio"].mean())
df[bool_series]["Model"].values

array(['Legend', '626', 'MPV'], dtype=object)

Calculate the average MPG ( ( MPG.city + MPG.highway)/2) for each of the carnmodels and add a new column called ‘AverageMPG’ to the updated dataframe.
1.   List the top 5 cars based on ‘AverageMPG’.
2.   Sort the “Midsize” cars by ‘AverageMPG’.
3.   Print all the non-USA cars (manufacturer and model) in alphabetical order whose ‘AverageMPG’ is higher than the average of the ‘AverageMPG’ column.

In [ ]:
df["AverageMPG"] = (df["MPG.city"]+df["MPG.highway"])/2
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Diff. in Price,Max_min_ratio,AverageMPG
Serial No.,,,,,,,,,,,,,,,,,,,,,
1,Acura,Legend,Small,12.9,15.9,18.8,25,31,None,Front,...,68,37,26.5,11.0,2705,non-USA,Acura Integra,5.9,1.457364,28.0
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,71,38,30.0,15.0,3560,non-USA,Acura Legend,9.5,1.325342,21.5
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,67,37,28.0,14.0,3375,non-USA,Audi 90,6.4,1.247104,23.0
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,70,37,31.0,17.0,3405,non-USA,Audi 100,13.8,1.448052,22.5
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,69,39,27.0,13.0,3640,non-USA,BMW 535i,12.5,1.527426,26.0

In [ ]:
df.sort_values(by=['AverageMPG'], ascending=False)["Make"].head(5)

Serial No.
39         Geo Metro
42       Honda Civic
83      Suzuki Swift
73    Pontiac LeMans
80      Subaru Justy
Name: Make, dtype: object

In [ ]:
df.loc[df["Type"] == "Midsize"].sort_values('AverageMPG')

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Diff. in Price,Max_min_ratio,AverageMPG
Serial No.,,,,,,,,,,,,,,,,,,,,,
48,Infiniti,Q45,Midsize,45.4,47.9,50.4,17,22,Driver only,Rear,...,72,42,29.0,15.0,4000,non-USA,Infiniti Q45,5.0,1.110132,19.5
50,Lexus,SC300,Midsize,34.7,35.2,35.6,18,23,Driver & Passenger,Rear,...,71,39,25.0,9.0,3515,non-USA,Lexus SC300,0.9,1.025937,20.5
11,Cadillac,Seville,Midsize,37.5,40.1,42.7,16,25,Driver & Passenger,Front,...,74,44,31.0,14.0,3935,USA,Cadillac Seville,5.2,1.138667,20.5
63,Mitsubishi,Diamante,Midsize,22.4,26.1,29.9,18,24,Driver only,Front,...,70,43,27.5,14.0,3730,non-USA,Mitsubishi Diamante,7.5,1.334821,21.0
49,Lexus,ES300,Midsize,27.5,28.0,28.4,18,24,Driver only,Front,...,70,40,27.5,14.0,3510,non-USA,Lexus ES300,0.9,1.032727,21.0
51,Lincoln,Continental,Midsize,33.3,34.3,35.3,17,26,Driver & Passenger,Front,...,73,42,30.0,19.0,3695,USA,Lincoln Continental,2.0,1.060060,21.5
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,71,38,30.0,15.0,3560,non-USA,Acura Legend,9.5,1.325342,21.5
59,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,19,25,Driver & Passenger,Rear,...,69,37,27.0,15.0,3525,non-USA,Mercedes-Benz 300E,36.2,1.826484,22.0
61,Mercury,Cougar,Midsize,14.9,14.9,14.9,19,26,None,Rear,...,73,38,28.0,15.0,3610,USA,Mercury Cougar,0.0,1.000000,22.5
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,70,37,31.0,17.0,3405,non-USA,Audi 100,13.8,1.448052,22.5
9,Buick,Riviera,Midsize,26.3,26.3,26.3,19,27,Driver only,Front,...,73,41,26.5,14.0,3495,USA,Buick Riviera,0.0,1.000000,23.0
76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,None,Front,...,72,41,28.5,16.0,3450,USA,Pontiac Grand_Prix,6.2,1.402597,23.0
47,Hyundai,Sonata,Midsize,12.4,13.9,15.3,20,27,None,Front,...,69,41,31.0,14.0,2885,non-USA,Hyundai Sonata,2.9,1.233871,23.5
67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,Front,...,69,41,28.5,14.0,3200,non-USA,Nissan Maxima,1.0,1.047619,23.5
27,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21,27,Driver only,Front,...,69,42,30.5,16.0,3080,USA,Dodge Dynasty,1.6,1.108108,24.0
93,Volvo,850,Midsize,24.8,26.7,28.5,20,28,Driver & Passenger,Front,...,69,38,30.0,15.0,3245,non-USA,Volvo 850,3.7,1.149194,24.0
15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,None,Front,...,71,40,28.5,16.0,3195,USA,Chevrolet Lumina,5.0,1.373134,25.0
37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,Front,...,71,40,27.5,18.0,3325,USA,Ford Taurus,9.2,1.589744,25.5
86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,Front,...,70,38,28.5,15.0,3030,non-USA,Toyota Camry,6.0,1.394737,25.5
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,69,39,27.0,13.0,3640,non-USA,BMW 535i,12.5,1.527426,26.0
6,Buick,Century,Midsize,14.2,15.7,17.3,22,31,Driver only,Front,...,69,41,28.0,16.0,2880,USA,Buick Century,3.1,1.218310,26.5
69,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23,31,Driver only,Front,...,70,42,28.0,16.0,2890,USA,Oldsmobile Cutlass_Ciera,4.2,1.295775,27.0

In [ ]:
df[(df['Origin']=='non-USA') & (df['AverageMPG'] > df['AverageMPG'].mean())][['Model','Manufacturer']]

              Model Manufacturer
Serial No.
1            Legend        Acura
5              535i          BMW
39            Metro          Geo
40            Storm          Geo
41          Prelude        Honda
42            Civic        Honda
43           Accord        Honda
44            Excel      Hyundai
46           Scoupe      Hyundai
53              323        Mazda
54          Protege        Mazda
55              626        Mazda
62           Mirage   Mitsubishi
64           Sentra       Nissan
65           Altima       Nissan
80            Justy       Subaru
81           Loyale       Subaru
82           Legacy       Subaru
83            Swift       Suzuki
84           Tercel       Toyota
85           Celica       Toyota
88              Fox   Volkswagen

Create a new identifier for the cars listed in the dataset by concatenating the first three alphabets of ‘Manufacturer’ with the first three alphabets of ‘Model’ followed by the horsepower. Use hyphens to indicate the concatenation. For example, the identifier for the first row is “Acu-Int-140”. Add a new column called ‘Identifier’ to the updated dataframe and generate
identifiers for each of the car models.

In [ ]:
df["Identifier"] = df.Manufacturer.str[:3] + '-' + df.Model.str[:3] + '-' + df.Horsepower.astype(str)
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Diff. in Price,Max_min_ratio,AverageMPG,Identifier
Serial No.,,,,,,,,,,,,,,,,,,,,,
1,Acura,Legend,Small,12.9,15.9,18.8,25,31,None,Front,...,37,26.5,11.0,2705,non-USA,Acura Integra,5.9,1.457364,28.0,Acu-Leg-140
2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,38,30.0,15.0,3560,non-USA,Acura Legend,9.5,1.325342,21.5,Acu-Leg-200
3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,37,28.0,14.0,3375,non-USA,Audi 90,6.4,1.247104,23.0,Aud-90-172
4,Audi,100,Midsize,30.8,37.7,44.6,19,26,Driver & Passenger,Front,...,37,31.0,17.0,3405,non-USA,Audi 100,13.8,1.448052,22.5,Aud-100-172
5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,39,27.0,13.0,3640,non-USA,BMW 535i,12.5,1.527426,26.0,BMW-535-208

Compare the average prices (average price is calculated after grouping them based on the ‘Type’) of different types (“Small”, “Midsize” etc.) of non-USA cars with that of the USA. Which one is cheaper in each category?

In [ ]:
df.groupby(['Type','Origin'])['Price'].mean()

Type     Origin
Compact  USA        12.828571
         non-USA    22.400000
Large    USA        24.300000
Midsize  USA        21.780000
         non-USA    31.750000
Small    USA        10.042857
         non-USA    10.228571
Sporty   USA        19.375000
         non-USA    19.416667
Van      USA        18.260000
         non-USA    20.150000
Name: Price, dtype: float64